apiVersion: apps/v1
kind: Deployment
metadata:
  name: oder
  labels:
    app: oder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oder
  template:
    metadata:
      labels:
        app: oder
    spec:
      containers:
        - name: oder
          image: "username/oder:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
